/**
 * server/repositories/scheduledVisits.ts  (Brick 10g)
 *
 * CRUD for scheduled_visits table.
 * All IDs are text (nanoid). No parseInt anywhere.
 * updated_at is set application-side on every UPDATE (no DB trigger).
 */

import { eq, and, gte, lte, desc, asc } from "drizzle-orm";
import { db } from "../db";
import {
  scheduledVisits,
  type InsertScheduledVisit,
  type ScheduledVisit,
} from "../../shared/schema-v2";

export const scheduledVisitsRepo = {
  // ── Reads ──────────────────────────────────────────────────────────────────

  /** All visits, newest scheduled_at first. */
  async getAll(): Promise<ScheduledVisit[]> {
    return db
      .select()
      .from(scheduledVisits)
      .orderBy(asc(scheduledVisits.scheduledAt));
  },

  /** Visits assigned to a specific tech (field_tech scoping). */
  async getByTech(techId: string): Promise<ScheduledVisit[]> {
    return db
      .select()
      .from(scheduledVisits)
      .where(eq(scheduledVisits.assignedTechId, techId))
      .orderBy(asc(scheduledVisits.scheduledAt));
  },

  /** Single visit by ID. */
  async getById(id: string): Promise<ScheduledVisit | undefined> {
    const rows = await db
      .select()
      .from(scheduledVisits)
      .where(eq(scheduledVisits.id, id))
      .limit(1);
    return rows[0];
  },

  /**
   * Date-range query for calendar feed.
   * fromIso / toIso are ISO 8601 strings (inclusive).
   * If techId provided, scopes to that tech's assignments.
   */
  async getByRange(
    fromIso: string,
    toIso: string,
    techId?: string,
  ): Promise<ScheduledVisit[]> {
    const conditions = [
      gte(scheduledVisits.scheduledAt, new Date(fromIso)),
      lte(scheduledVisits.scheduledAt, new Date(toIso)),
    ];
    if (techId) conditions.push(eq(scheduledVisits.assignedTechId, techId));

    return db
      .select()
      .from(scheduledVisits)
      .where(and(...conditions))
      .orderBy(asc(scheduledVisits.scheduledAt));
  },

  // ── Writes ─────────────────────────────────────────────────────────────────

  /** Create a new scheduled visit. ID generated by schema $defaultFn. */
  async create(data: InsertScheduledVisit): Promise<ScheduledVisit> {
    const rows = await db
      .insert(scheduledVisits)
      .values(data)
      .returning();
    return rows[0];
  },

  /**
   * Update a visit. Sets updated_at = now() application-side (no trigger).
   * Returns undefined if not found.
   */
  async update(
    id: string,
    patch: Partial<Pick<
      ScheduledVisit,
      | "assignedTechId"
      | "visitType"
      | "scheduledAt"
      | "status"
      | "followUpOf"
      | "notes"
    >>,
  ): Promise<ScheduledVisit | undefined> {
    const rows = await db
      .update(scheduledVisits)
      .set({ ...patch, updatedAt: new Date() })   // application-level updated_at
      .where(eq(scheduledVisits.id, id))
      .returning();
    return rows[0];
  },
};
