/**
 * server/repositories/shorelineMarkers.ts  (Brick 10e-prereq)
 *
 * CRUD for shoreline_markers table.
 * All IDs are text (nanoid). No parseInt anywhere.
 * lat/lng are numeric(9,6) — returned as string by Drizzle/pg driver.
 */

import { eq } from "drizzle-orm";
import { db } from "../db";
import {
  shorelineMarkers,
  type InsertShorelineMarker,
} from "../../shared/schema-v2";

export const shorelineMarkersRepo = {
  /** All markers, optionally filtered by lake name. */
  async getAll(lake?: string) {
    if (lake) {
      return db
        .select()
        .from(shorelineMarkers)
        .where(eq(shorelineMarkers.lake, lake))
        .orderBy(shorelineMarkers.markerNumber);
    }
    return db
      .select()
      .from(shorelineMarkers)
      .orderBy(shorelineMarkers.lake, shorelineMarkers.markerNumber);
  },

  /** Single marker by text ID. */
  async getById(id: string) {
    const [row] = await db
      .select()
      .from(shorelineMarkers)
      .where(eq(shorelineMarkers.id, id));
    return row ?? null;
  },

  /** All markers for a specific lake, ordered by markerNumber. */
  async getByLake(lake: string) {
    return db
      .select()
      .from(shorelineMarkers)
      .where(eq(shorelineMarkers.lake, lake))
      .orderBy(shorelineMarkers.markerNumber);
  },

  /** Insert a new marker. ID is generated by nanoid() via the schema default. */
  async create(data: InsertShorelineMarker) {
    const [row] = await db
      .insert(shorelineMarkers)
      .values(data)
      .returning();
    return row;
  },
};
